apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      test: web
  template:
    metadata:
      labels:
        test: web
    spec:
      containers:
        - name: test-container
          image: test-prod
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: test-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    test: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
